# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(669, 268)
        Form.setAutoFillBackground(False)
        Form.setStyleSheet("QWidget {\n"
"    background-color: #ffffff;\n"
"}")
        self.gridLayout_3 = QtWidgets.QGridLayout(Form)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.listWidget = QtWidgets.QListWidget(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setMinimumSize(QtCore.QSize(200, 0))
        self.listWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.listWidget.setObjectName("listWidget")
        self.gridLayout_2.addWidget(self.listWidget, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnRemoveListItem = QtWidgets.QPushButton(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnRemoveListItem.sizePolicy().hasHeightForWidth())
        self.btnRemoveListItem.setSizePolicy(sizePolicy)
        self.btnRemoveListItem.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnRemoveListItem.setStyleSheet("QPushButton {\n"
"    border: 1px solid #000000;\n"
"    border-radius: 10px;\n"
"    background-color: #ffffff;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    border: 1px solid #888888;\n"
"    background-color: #dcdcdc;\n"
"    color: #aaaaaa;\n"
"}\n"
"")
        self.btnRemoveListItem.setObjectName("btnRemoveListItem")
        self.horizontalLayout_2.addWidget(self.btnRemoveListItem)
        self.btnCopyListItem = QtWidgets.QPushButton(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCopyListItem.sizePolicy().hasHeightForWidth())
        self.btnCopyListItem.setSizePolicy(sizePolicy)
        self.btnCopyListItem.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnCopyListItem.setStyleSheet("QPushButton {\n"
"    border: 1px solid #000000;\n"
"    border-radius: 10px;\n"
"    background-color: #ffffff;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    border: 1px solid #888888;\n"
"    background-color: #dcdcdc;\n"
"    color: #aaaaaa;\n"
"}\n"
"")
        self.btnCopyListItem.setObjectName("btnCopyListItem")
        self.horizontalLayout_2.addWidget(self.btnCopyListItem)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 3, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.imgSearch = QtWidgets.QLabel(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imgSearch.sizePolicy().hasHeightForWidth())
        self.imgSearch.setSizePolicy(sizePolicy)
        self.imgSearch.setMaximumSize(QtCore.QSize(20, 20))
        self.imgSearch.setText("")
        self.imgSearch.setPixmap(QtGui.QPixmap("icons:PixelPerfect_search.png"))
        self.imgSearch.setScaledContents(True)
        self.imgSearch.setObjectName("imgSearch")
        self.horizontalLayout_8.addWidget(self.imgSearch)
        self.txtSearchListItem = QtWidgets.QPlainTextEdit(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtSearchListItem.sizePolicy().hasHeightForWidth())
        self.txtSearchListItem.setSizePolicy(sizePolicy)
        self.txtSearchListItem.setMaximumSize(QtCore.QSize(16777215, 30))
        self.txtSearchListItem.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.txtSearchListItem.setStyleSheet("QPlainTextEdit {\n"
"    border: 2px solid #3498db;\n"
"    border-radius: 10px;\n"
"    background-color: #ffffff;\n"
"    padding: 1px;\n"
"}")
        self.txtSearchListItem.setObjectName("txtSearchListItem")
        self.horizontalLayout_8.addWidget(self.txtSearchListItem)
        self.gridLayout_2.addLayout(self.horizontalLayout_8, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.imgClipboard = QtWidgets.QLabel(parent=Form)
        self.imgClipboard.setStyleSheet("QLabel {\n"
"    border: 2px solid #3498db;\n"
"    border-radius: 10px;\n"
"    padding: 6px;\n"
"}")
        self.imgClipboard.setText("")
        self.imgClipboard.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.imgClipboard.setObjectName("imgClipboard")
        self.verticalLayout.addWidget(self.imgClipboard)
        self.txtClipboard = QtWidgets.QPlainTextEdit(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtClipboard.sizePolicy().hasHeightForWidth())
        self.txtClipboard.setSizePolicy(sizePolicy)
        self.txtClipboard.setMinimumSize(QtCore.QSize(0, 50))
        self.txtClipboard.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txtClipboard.setFont(font)
        self.txtClipboard.setStyleSheet("QPlainTextEdit {\n"
"    border: 2px solid #3498db;\n"
"    border-radius: 10px;\n"
"    background-color: #ffffff;\n"
"    padding: 6px;\n"
"}")
        self.txtClipboard.setObjectName("txtClipboard")
        self.verticalLayout.addWidget(self.txtClipboard)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.btnReloadContent = QtWidgets.QPushButton(parent=Form)
        self.btnReloadContent.setEnabled(True)
        self.btnReloadContent.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnReloadContent.setStyleSheet("QPushButton {\n"
"    border: 1px solid #000000;\n"
"    border-radius: 10px;\n"
"    background-color: #ffffff;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    border: 1px solid #888888;\n"
"    background-color: #dcdcdc;\n"
"    color: #aaaaaa;\n"
"}\n"
"")
        self.btnReloadContent.setObjectName("btnReloadContent")
        self.horizontalLayout_15.addWidget(self.btnReloadContent)
        self.btnCopyContent = QtWidgets.QPushButton(parent=Form)
        self.btnCopyContent.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnCopyContent.setStyleSheet("QPushButton {\n"
"    border: 1px solid #000000;\n"
"    border-radius: 10px;\n"
"    background-color: #ffffff;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    border: 1px solid #888888;\n"
"    background-color: #dcdcdc;\n"
"    color: #aaaaaa;\n"
"}\n"
"")
        self.btnCopyContent.setObjectName("btnCopyContent")
        self.horizontalLayout_15.addWidget(self.btnCopyContent)
        self.verticalLayout.addLayout(self.horizontalLayout_15)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btnSaveData = QtWidgets.QPushButton(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSaveData.sizePolicy().hasHeightForWidth())
        self.btnSaveData.setSizePolicy(sizePolicy)
        self.btnSaveData.setMinimumSize(QtCore.QSize(100, 100))
        self.btnSaveData.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btnSaveData.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnSaveData.setStyleSheet("QPushButton {\n"
"    border: 1px solid #000000;\n"
"    border-radius: 10px;\n"
"    background-color: #ffffff;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    border: 1px solid #888888;\n"
"    background-color: #dcdcdc;\n"
"    color: #aaaaaa;\n"
"}\n"
"")
        self.btnSaveData.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons:PixelPerfect_download.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnSaveData.setIcon(icon)
        self.btnSaveData.setIconSize(QtCore.QSize(90, 90))
        self.btnSaveData.setObjectName("btnSaveData")
        self.horizontalLayout_4.addWidget(self.btnSaveData)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.lblSaveImage = QtWidgets.QLabel(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSaveImage.sizePolicy().hasHeightForWidth())
        self.lblSaveImage.setSizePolicy(sizePolicy)
        self.lblSaveImage.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lblSaveImage.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblSaveImage.setObjectName("lblSaveImage")
        self.verticalLayout_4.addWidget(self.lblSaveImage)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btnToggleSlash = QtWidgets.QPushButton(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnToggleSlash.sizePolicy().hasHeightForWidth())
        self.btnToggleSlash.setSizePolicy(sizePolicy)
        self.btnToggleSlash.setMinimumSize(QtCore.QSize(100, 100))
        self.btnToggleSlash.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btnToggleSlash.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnToggleSlash.setStyleSheet("QPushButton {\n"
"    border: 1px solid #000000;\n"
"    border-radius: 10px;\n"
"    background-color: #ffffff;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    border: 1px solid #888888;\n"
"    background-color: #dcdcdc;\n"
"    color: #aaaaaa;\n"
"}\n"
"")
        self.btnToggleSlash.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons:IconsBox_slash.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnToggleSlash.setIcon(icon1)
        self.btnToggleSlash.setIconSize(QtCore.QSize(90, 90))
        self.btnToggleSlash.setCheckable(False)
        self.btnToggleSlash.setObjectName("btnToggleSlash")
        self.horizontalLayout_5.addWidget(self.btnToggleSlash)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.lblToggleSlash = QtWidgets.QLabel(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblToggleSlash.sizePolicy().hasHeightForWidth())
        self.lblToggleSlash.setSizePolicy(sizePolicy)
        self.lblToggleSlash.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lblToggleSlash.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblToggleSlash.setObjectName("lblToggleSlash")
        self.verticalLayout_5.addWidget(self.lblToggleSlash)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.btnConvertQR = QtWidgets.QPushButton(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnConvertQR.sizePolicy().hasHeightForWidth())
        self.btnConvertQR.setSizePolicy(sizePolicy)
        self.btnConvertQR.setMinimumSize(QtCore.QSize(100, 100))
        self.btnConvertQR.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btnConvertQR.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnConvertQR.setAutoFillBackground(False)
        self.btnConvertQR.setStyleSheet("QPushButton {\n"
"    border: 1px solid #000000;\n"
"    border-radius: 10px;\n"
"    background-color: #ffffff;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    border: 1px solid #888888;\n"
"    background-color: #dcdcdc;\n"
"    color: #aaaaaa;\n"
"}\n"
"")
        self.btnConvertQR.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons:kawalanicon_qrcode.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnConvertQR.setIcon(icon2)
        self.btnConvertQR.setIconSize(QtCore.QSize(90, 90))
        self.btnConvertQR.setShortcut("")
        self.btnConvertQR.setObjectName("btnConvertQR")
        self.horizontalLayout_6.addWidget(self.btnConvertQR)
        self.verticalLayout_8.addLayout(self.horizontalLayout_6)
        self.lblConvertQR = QtWidgets.QLabel(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblConvertQR.sizePolicy().hasHeightForWidth())
        self.lblConvertQR.setSizePolicy(sizePolicy)
        self.lblConvertQR.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lblConvertQR.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblConvertQR.setWordWrap(False)
        self.lblConvertQR.setObjectName("lblConvertQR")
        self.verticalLayout_8.addWidget(self.lblConvertQR)
        self.horizontalLayout.addLayout(self.verticalLayout_8)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.btnOpenSetting = QtWidgets.QPushButton(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnOpenSetting.sizePolicy().hasHeightForWidth())
        self.btnOpenSetting.setSizePolicy(sizePolicy)
        self.btnOpenSetting.setMinimumSize(QtCore.QSize(100, 100))
        self.btnOpenSetting.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btnOpenSetting.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnOpenSetting.setAutoFillBackground(False)
        self.btnOpenSetting.setStyleSheet("QPushButton {\n"
"    border: 1px solid #000000;\n"
"    border-radius: 10px;\n"
"    background-color: #ffffff;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    border: 1px solid #888888;\n"
"    background-color: #dcdcdc;\n"
"    color: #aaaaaa;\n"
"}\n"
"")
        self.btnOpenSetting.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons:PixelPerfect_settings.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnOpenSetting.setIcon(icon3)
        self.btnOpenSetting.setIconSize(QtCore.QSize(90, 90))
        self.btnOpenSetting.setShortcut("")
        self.btnOpenSetting.setObjectName("btnOpenSetting")
        self.horizontalLayout_17.addWidget(self.btnOpenSetting)
        self.verticalLayout_13.addLayout(self.horizontalLayout_17)
        self.lblOpenSetting = QtWidgets.QLabel(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblOpenSetting.sizePolicy().hasHeightForWidth())
        self.lblOpenSetting.setSizePolicy(sizePolicy)
        self.lblOpenSetting.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lblOpenSetting.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblOpenSetting.setWordWrap(False)
        self.lblOpenSetting.setObjectName("lblOpenSetting")
        self.verticalLayout_13.addWidget(self.lblOpenSetting)
        self.horizontalLayout.addLayout(self.verticalLayout_13)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Clipboard Manager"))
        self.btnRemoveListItem.setText(_translate("Form", "Remove"))
        self.btnCopyListItem.setText(_translate("Form", "Copy"))
        self.txtSearchListItem.setPlaceholderText(_translate("Form", "Search"))
        self.txtClipboard.setPlaceholderText(_translate("Form", "Edit clipboard content here..."))
        self.btnReloadContent.setText(_translate("Form", "Reload"))
        self.btnCopyContent.setText(_translate("Form", "Copy"))
        self.lblSaveImage.setText(_translate("Form", "Save Text / Image"))
        self.lblToggleSlash.setText(_translate("Form", "Forward <=> Back"))
        self.lblConvertQR.setText(_translate("Form", "QR Reader / Generator"))
        self.lblOpenSetting.setText(_translate("Form", "Open Setting"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
